_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 2
                - 55
            "4": 3.12.1
            "5": 0.20.1
            "8":
                - 1
            "9":
                "1": llmapps_intro
            "12": 0.20.1
            "13": linux-x86_64
